options = 
{
	["difficulty"] = 
	{
		["fuel"] = false,
		["spottingDot"] = 3,
		["miniHUD"] = false,
		["optionsView"] = "optview_all",
		["setGlobal"] = true,
		["avionicsLanguage"] = "native",
		["cockpitVisualRM"] = false,
		["map"] = true,
		["gWarmUp"] = false,
		["spectatorExternalViews"] = true,
		["userMarks"] = true,
		["iconsTheme"] = "nato",
		["weapons"] = false,
		["padlock"] = true,
		["birds"] = 0,
		["permitCrash"] = true,
		["immortal"] = false,
		["cockpitStatusBarAllowed"] = false,
		["wakeTurbulence"] = false,
		["easyFlight"] = false,
		["hideStick"] = false,
		["radio"] = false,
		["geffect"] = "realistic",
		["easyCommunication"] = true,
		["reports"] = true,
		["tips"] = true,
		["units"] = "imperial",
		["autoTrimmer"] = false,
		["controlsIndicator"] = true,
		["externalViews"] = true,
		["RBDAI"] = true,
		["userSnapView"] = true,
		["unrestrictedSATNAV"] = false,
		["labels"] = 1,
	}, -- end of ["difficulty"]
	["views"] = 
	{
		["cockpit"] = 
		{
			["mirrors"] = false,
			["avionics"] = 0,
		}, -- end of ["cockpit"]
	}, -- end of ["views"]
	["VR"] = 
	{
		["enable"] = false,
		["box_mouse_cursor"] = true,
		["pixel_density"] = 1,
		["use_mouse"] = true,
		["mirror_use_DCS_resolution"] = false,
		["bloom"] = true,
		["mirror_source"] = 0,
		["msaaMaskSize"] = 0.42,
		["mirror_crop"] = false,
	}, -- end of ["VR"]
	["graphics"] = 
	{
		["volumetricLights"] = 1,
		["AA"] = "OFF",
		["forestDetailsFactor"] = 1,
		["rainDroplets"] = 0,
		["LensEffects"] = 3,
		["heatBlr"] = 0,
		["anisotropy"] = 4,
		["water"] = 2,
		["motionBlurAmount"] = 1,
		["BlurFlatShadows"] = 0,
		["visibRange"] = "High",
		["lights"] = 2,
		["shadows"] = 2,
		["MSAA"] = 1,
		["canopyReflections"] = 1,
		["ScreenshotExt"] = "jpg",
		["clutterMaxDistance"] = 0,
		["cockpitGI"] = 1,
		["terrainTextures"] = "min",
		["multiMonitorSetup"] = "1camera",
		["defaultFOV"] = 78,
		["shadowTree"] = false,
		["chimneySmokeDensity"] = 4,
		["civTraffic"] = "",
		["SSS"] = 0,
		["fullScreen"] = false,
		["preloadRadius"] = 150000,
		["secondaryShadows"] = 0,
		["Scaling"] = 0.66,
		["DOF"] = 0,
		["clouds"] = 1,
		["sceneryDetailsFactor"] = 1,
		["Upscaling"] = "OFF",
		["Sharpening"] = 0,
		["textures"] = 0,
		["forestDistanceFactor"] = 0.5,
		["useDeferredShading"] = 1,
		["SSLR"] = 0,
		["effects"] = 3,
		["SSAO"] = 0,
		["motionBlur"] = 0,
		["sync"] = false,
		["outputGamma"] = 2.2,
		["scaleGui"] = 1,
		["flatTerrainShadows"] = 0,
		["messagesFontScale"] = 1,
		["DLSS_PerfQuality"] = 0,
	}, -- end of ["graphics"]
	["plugins"] = {
		["Tacview"] = {
			["tacviewExportPath"] = "C:\\DCS_configs\\Tacview",
		},
	}, -- end of ["plugins"]
	["format"] = 1,
	["sound"] = 
	{
		["main_output"] = "",
		["FakeAfterburner"] = false,
		["volume"] = 80,
		["headphones_on_external_views"] = true,
		["switches"] = 100,
		["subtitles"] = true,
		["world"] = 100,
		["hear_in_helmet"] = false,
		["cockpit"] = 100,
		["music"] = 60,
		["main_layout"] = "",
		["headphones"] = 100,
		["hp_output"] = "",
		["voice_chat_output"] = "",
		["voice_chat"] = true,
		["GBreathEffect"] = true,
		["radioSpeech"] = true,
		["voiceChatInSensitivity"] = -50,
		["play_audio_while_minimized"] = false,
		["voiceChatInVolume"] = 50,
		["microphone_use"] = 2,
		["voice_chat_input"] = "",
		["gui"] = 100,
	}, -- end of ["sound"]
	["miscellaneous"] = 
	{
		["chat_window_at_start"] = true,
		["TrackIR_external_views"] = true,
		["f11_free_camera"] = true,
		["f10_awacs"] = true,
		["Coordinate_Display"] = "Lat Long",
		["accidental_failures"] = false,
		["autologin"] = true,
		["force_feedback_enabled"] = true,
		["allow_server_screenshots"] = false,
		["synchronize_controls"] = false,
		["headmove"] = false,
		["f5_nearest_ac"] = true,
		["F2_view_effects"] = 1,
		["launcher"] = false,
		["mgrs_grid_visible"] = true,
		["show_pilot_body"] = false,
		["geo_grid_visible"] = false,
		["collect_stat"] = false,
	}, -- end of ["miscellaneous"]
} -- end of options
